# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'movieWorld.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 0, 381, 341))
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(120, 30, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 70, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(130, 110, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 30, 61, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(226, 63, 71, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(236, 110, 51, 20))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(130, 160, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(230, 160, 81, 16))
        self.label_12.setObjectName("label_12")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMovies = QtWidgets.QMenu(self.menubar)
        self.menuMovies.setObjectName("menuMovies")
        self.menuCategory_ID = QtWidgets.QMenu(self.menubar)
        self.menuCategory_ID.setObjectName("menuCategory_ID")
        self.menuCategory_Name = QtWidgets.QMenu(self.menubar)
        self.menuCategory_Name.setObjectName("menuCategory_Name")
        self.menuMovie_Name = QtWidgets.QMenu(self.menubar)
        self.menuMovie_Name.setObjectName("menuMovie_Name")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMovies.menuAction())
        self.menubar.addAction(self.menuCategory_ID.menuAction())
        self.menubar.addAction(self.menuCategory_Name.menuAction())
        self.menubar.addAction(self.menuMovie_Name.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MovieWorld"))
        self.label.setText(_translate("MainWindow", "category_id"))
        self.label_2.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "2"))
        self.label_4.setText(_translate("MainWindow", "category_desc"))
        self.label_5.setText(_translate("MainWindow", "Comedy"))
        self.label_6.setText(_translate("MainWindow", "Animation"))
        self.label_7.setText(_translate("MainWindow", "movie_title"))
        self.label_8.setText(_translate("MainWindow", "Funny champ"))
        self.label_9.setText(_translate("MainWindow", "Boss Baby"))
        self.label_10.setText(_translate("MainWindow", "3"))
        self.label_11.setText(_translate("MainWindow", "Horror"))
        self.label_12.setText(_translate("MainWindow", "Ghosted House"))
        self.menuMovies.setTitle(_translate("MainWindow", "Movies"))
        self.menuCategory_ID.setTitle(_translate("MainWindow", "Category ID"))
        self.menuCategory_Name.setTitle(_translate("MainWindow", "Category Description"))
        self.menuMovie_Name.setTitle(_translate("MainWindow", "Movie Title"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
