# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kasi-cookingTour_Event.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 441, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 160, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 100, 101, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(160, 130, 101, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 160, 101, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(280, 50, 231, 141))
        self.mdiArea.setObjectName("mdiArea")
        self.subwindow = QtWidgets.QWidget()
        self.subwindow.setObjectName("subwindow")
        self.label_6 = QtWidgets.QLabel(self.subwindow)
        self.label_6.setGeometry(QtCore.QRect(100, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.subwindow)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 71, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.subwindow)
        self.label_8.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.label_8.setObjectName("label_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.subwindow)
        self.pushButton_4.setGeometry(QtCore.QRect(90, 80, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.mdiArea_2 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea_2.setGeometry(QtCore.QRect(0, 240, 281, 311))
        self.mdiArea_2.setObjectName("mdiArea_2")
        self.subwindow_2 = QtWidgets.QWidget()
        self.subwindow_2.setObjectName("subwindow_2")
        self.label_9 = QtWidgets.QLabel(self.subwindow_2)
        self.label_9.setGeometry(QtCore.QRect(80, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.subwindow_2)
        self.label_10.setGeometry(QtCore.QRect(10, 40, 231, 21))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.subwindow_2)
        self.label_11.setGeometry(QtCore.QRect(60, 140, 191, 21))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.subwindow_2)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 41, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.subwindow_2)
        self.label_13.setGeometry(QtCore.QRect(10, 100, 71, 16))
        self.label_13.setObjectName("label_13")
        self.dateEdit = QtWidgets.QDateEdit(self.subwindow_2)
        self.dateEdit.setGeometry(QtCore.QRect(70, 70, 110, 22))
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 8, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.subwindow_2)
        self.timeEdit.setGeometry(QtCore.QRect(80, 100, 121, 21))
        self.timeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 8, 1), QtCore.QTime(9, 0, 0)))
        self.timeEdit.setObjectName("timeEdit")
        self.label_14 = QtWidgets.QLabel(self.subwindow_2)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.label_14.setObjectName("label_14")
        self.timeEdit1 = QtWidgets.QTimeEdit(self.subwindow_2)
        self.timeEdit1.setGeometry(QtCore.QRect(50, 130, 81, 21))
        self.timeEdit1.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 8, 1), QtCore.QTime(18, 30, 0)))
        self.timeEdit1.setObjectName("timeEdit1")
        self.label_15 = QtWidgets.QLabel(self.subwindow_2)
        self.label_15.setGeometry(QtCore.QRect(10, 160, 131, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.subwindow_2)
        self.label_16.setGeometry(QtCore.QRect(0, 220, 261, 21))
        self.label_16.setObjectName("label_16")
        self.label_23 = QtWidgets.QLabel(self.subwindow_2)
        self.label_23.setGeometry(QtCore.QRect(10, 190, 121, 16))
        self.label_23.setObjectName("label_23")
        self.pushButton_5 = QtWidgets.QPushButton(self.subwindow_2)
        self.pushButton_5.setGeometry(QtCore.QRect(80, 250, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.mdiArea_3 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea_3.setGeometry(QtCore.QRect(260, 250, 321, 281))
        self.mdiArea_3.setObjectName("mdiArea_3")
        self.subwindow_3 = QtWidgets.QWidget()
        self.subwindow_3.setObjectName("subwindow_3")
        self.label_17 = QtWidgets.QLabel(self.subwindow_3)
        self.label_17.setGeometry(QtCore.QRect(110, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.subwindow_3)
        self.label_18.setGeometry(QtCore.QRect(10, 30, 281, 21))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.subwindow_3)
        self.label_19.setGeometry(QtCore.QRect(10, 60, 47, 13))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.subwindow_3)
        self.label_20.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.subwindow_3)
        self.label_21.setGeometry(QtCore.QRect(20, 110, 47, 20))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.subwindow_3)
        self.label_22.setGeometry(QtCore.QRect(10, 140, 201, 21))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.subwindow_3)
        self.label_24.setGeometry(QtCore.QRect(10, 170, 121, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.subwindow_3)
        self.label_25.setGeometry(QtCore.QRect(0, 200, 211, 16))
        self.label_25.setObjectName("label_25")
        self.pushButton_6 = QtWidgets.QPushButton(self.subwindow_3)
        self.pushButton_6.setGeometry(QtCore.QRect(80, 220, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.subwindow_3)
        self.dateEdit_2.setGeometry(QtCore.QRect(50, 50, 110, 22))
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 8, 15), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.subwindow_3)
        self.timeEdit_2.setGeometry(QtCore.QRect(80, 80, 118, 22))
        self.timeEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(10, 0, 0)))
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.subwindow_3)
        self.timeEdit_3.setGeometry(QtCore.QRect(80, 120, 118, 22))
        self.timeEdit_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(22, 0, 0)))
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.label_21.raise_()
        self.label_22.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.pushButton_6.raise_()
        self.dateEdit_2.raise_()
        self.timeEdit_2.raise_()
        self.timeEdit_3.raise_()
        self.mdiArea_4 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea_4.setGeometry(QtCore.QRect(510, 280, 291, 291))
        self.mdiArea_4.setObjectName("mdiArea_4")
        self.subwindow_4 = QtWidgets.QWidget()
        self.subwindow_4.setObjectName("subwindow_4")
        self.label_26 = QtWidgets.QLabel(self.subwindow_4)
        self.label_26.setGeometry(QtCore.QRect(70, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.subwindow_4)
        self.label_27.setGeometry(QtCore.QRect(10, 40, 261, 21))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.subwindow_4)
        self.label_28.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.subwindow_4)
        self.label_29.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.subwindow_4)
        self.label_30.setGeometry(QtCore.QRect(10, 120, 47, 13))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.subwindow_4)
        self.label_31.setGeometry(QtCore.QRect(10, 150, 151, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.subwindow_4)
        self.label_32.setGeometry(QtCore.QRect(10, 180, 121, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.subwindow_4)
        self.label_33.setGeometry(QtCore.QRect(10, 200, 241, 21))
        self.label_33.setObjectName("label_33")
        self.pushButton_7 = QtWidgets.QPushButton(self.subwindow_4)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 220, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.subwindow_4)
        self.dateEdit_3.setGeometry(QtCore.QRect(50, 60, 110, 22))
        self.dateEdit_3.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 8, 30), QtCore.QTime(0, 0, 0)))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.subwindow_4)
        self.timeEdit_4.setGeometry(QtCore.QRect(90, 90, 118, 22))
        self.timeEdit_4.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(8, 0, 0)))
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.timeEdit_5 = QtWidgets.QTimeEdit(self.subwindow_4)
        self.timeEdit_5.setGeometry(QtCore.QRect(40, 120, 118, 22))
        self.timeEdit_5.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(20, 0, 0)))
        self.timeEdit_5.setObjectName("timeEdit_5")
        self.mdiArea_5 = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea_5.setGeometry(QtCore.QRect(520, 0, 261, 221))
        self.mdiArea_5.setObjectName("mdiArea_5")
        self.subwindow_5 = QtWidgets.QWidget()
        self.subwindow_5.setObjectName("subwindow_5")
        self.label_34 = QtWidgets.QLabel(self.subwindow_5)
        self.label_34.setGeometry(QtCore.QRect(70, 13, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.subwindow_5)
        self.label_35.setGeometry(QtCore.QRect(20, 50, 47, 13))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.subwindow_5)
        self.label_36.setGeometry(QtCore.QRect(10, 80, 47, 13))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.subwindow_5)
        self.label_37.setGeometry(QtCore.QRect(80, 90, 61, 20))
        self.label_37.setObjectName("label_37")
        self.pushButton_8 = QtWidgets.QPushButton(self.subwindow_5)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 120, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.subwindow_5)
        self.pushButton_9.setGeometry(QtCore.QRect(130, 120, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_38 = QtWidgets.QLabel(self.subwindow_5)
        self.label_38.setGeometry(QtCore.QRect(10, 150, 211, 21))
        self.label_38.setObjectName("label_38")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(90, 200, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuHOME = QtWidgets.QMenu(self.menubar)
        self.menuHOME.setObjectName("menuHOME")
        self.menuSIGN_IN = QtWidgets.QMenu(self.menubar)
        self.menuSIGN_IN.setObjectName("menuSIGN_IN")
        self.menuKOTA_MARKET = QtWidgets.QMenu(self.menubar)
        self.menuKOTA_MARKET.setObjectName("menuKOTA_MARKET")
        self.menuPIZZA_SUNDAY = QtWidgets.QMenu(self.menubar)
        self.menuPIZZA_SUNDAY.setObjectName("menuPIZZA_SUNDAY")
        self.menuFISH_n_CHIPS = QtWidgets.QMenu(self.menubar)
        self.menuFISH_n_CHIPS.setObjectName("menuFISH_n_CHIPS")
        self.menuRESERVATIO = QtWidgets.QMenu(self.menubar)
        self.menuRESERVATIO.setObjectName("menuRESERVATIO")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHOME.menuAction())
        self.menubar.addAction(self.menuSIGN_IN.menuAction())
        self.menubar.addAction(self.menuKOTA_MARKET.menuAction())
        self.menubar.addAction(self.menuPIZZA_SUNDAY.menuAction())
        self.menubar.addAction(self.menuFISH_n_CHIPS.menuAction())
        self.menubar.addAction(self.menuRESERVATIO.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "KASI COOKING-TOUR EVENTS"))
        self.label_2.setText(_translate("MainWindow", "WELCOME to KASI-COOKING EVENTs.."))
        self.label_3.setText(_translate("MainWindow", "KOTA MARKET"))
        self.label_4.setText(_translate("MainWindow", "PIZZA SUNDAY"))
        self.label_5.setText(_translate("MainWindow", "FISH n CHIPS FEST"))
        self.pushButton.setText(_translate("MainWindow", "EVENT DETAILS"))
        self.pushButton_2.setText(_translate("MainWindow", "EVENT DETAILS"))
        self.pushButton_3.setText(_translate("MainWindow", "EVENT DETAILS"))
        self.subwindow.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_6.setText(_translate("MainWindow", "SIGN - IN >>"))
        self.label_7.setText(_translate("MainWindow", "NAME"))
        self.label_8.setText(_translate("MainWindow", "CELL NO."))
        self.pushButton_4.setText(_translate("MainWindow", "SIGN "))
        self.subwindow_2.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_9.setText(_translate("MainWindow", "KOTA MARKET"))
        self.label_10.setText(_translate("MainWindow", "VENUE :: JABULANI MALL 112 MOLOTO STREET"))
        self.label_12.setText(_translate("MainWindow", "DATE"))
        self.label_13.setText(_translate("MainWindow", "START TIME"))
        self.label_14.setText(_translate("MainWindow", "END :"))
        self.label_15.setText(_translate("MainWindow", "CAPACITY :: 50 GUESTS"))
        self.label_16.setText(_translate("MainWindow", "EVENT MANAGER @ 0833968521 or email km@gmail.com"))
        self.label_23.setText(_translate("MainWindow", "ENTRANCE :: R50"))
        self.pushButton_5.setText(_translate("MainWindow", "GOING >>>"))
        self.subwindow_3.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_17.setText(_translate("MainWindow", "PIZZA SUNDAY"))
        self.label_18.setText(_translate("MainWindow", "VENUE :: THOKOZA PARK 1236 PIMVILLE SOWETO"))
        self.label_19.setText(_translate("MainWindow", "DATE"))
        self.label_20.setText(_translate("MainWindow", "START TIME"))
        self.label_21.setText(_translate("MainWindow", "END"))
        self.label_22.setText(_translate("MainWindow", "CAPACITY :: 40 GUESTS"))
        self.label_24.setText(_translate("MainWindow", "ENTRANCE :: R70"))
        self.label_25.setText(_translate("MainWindow", "MANAGER @ 0732547896 or bs@gmail.com"))
        self.pushButton_6.setText(_translate("MainWindow", "GOING >>>"))
        self.subwindow_4.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_26.setText(_translate("MainWindow", "FISH n CHIPS FEST"))
        self.label_27.setText(_translate("MainWindow", "VENUE :: DOROTHY MALL 2369 DOBSONVILLE SOWETO"))
        self.label_28.setText(_translate("MainWindow", "DATE"))
        self.label_29.setText(_translate("MainWindow", "START TIME "))
        self.label_30.setText(_translate("MainWindow", "END"))
        self.label_31.setText(_translate("MainWindow", "CAPACITY :: 25 GUESTS"))
        self.label_32.setText(_translate("MainWindow", "ENTRANCE :: R100"))
        self.label_33.setText(_translate("MainWindow", "MANAGER @ 0812369874 or fnc@gmail.com"))
        self.pushButton_7.setText(_translate("MainWindow", "GOING >>>"))
        self.subwindow_5.setWindowTitle(_translate("MainWindow", "Subwindow"))
        self.label_34.setText(_translate("MainWindow", "RESERVATION"))
        self.label_35.setText(_translate("MainWindow", "NAME"))
        self.label_36.setText(_translate("MainWindow", "CELL NO."))
        self.label_37.setText(_translate("MainWindow", "PAYMENT"))
        self.pushButton_8.setText(_translate("MainWindow", "EFT"))
        self.pushButton_9.setText(_translate("MainWindow", "ONLINE"))
        self.label_38.setText(_translate("MainWindow", "AFTER PAYMENT YOU RECEIVE A RECEIPT"))
        self.pushButton_10.setText(_translate("MainWindow", "SIGN IN>>"))
        self.menuHOME.setTitle(_translate("MainWindow", "HOME"))
        self.menuSIGN_IN.setTitle(_translate("MainWindow", "SIGN IN"))
        self.menuKOTA_MARKET.setTitle(_translate("MainWindow", "KOTA MARKET"))
        self.menuPIZZA_SUNDAY.setTitle(_translate("MainWindow", "PIZZA SUNDAY"))
        self.menuFISH_n_CHIPS.setTitle(_translate("MainWindow", "FISH n CHIPS"))
        self.menuRESERVATIO.setTitle(_translate("MainWindow", "RESERVATIO"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

